### PR TITLE
Implement sorting by time.

### PR DESCRIPTION
**Pull request by natask**
apply delve--flatten on args to db query
 add ctime support.
 sort by atime, ctime, mtime.
 modify ui to depict all.

### CODE REVIEW

**Comment by publicimageltd** [comment]
I just noticed that my local copy is 50 commits ahead; including a rewrite of the query function. Should have merged it, but didn't. So there will be a conflict for sure.

Do you happen to know how I could fetch your changes locally, to have a look how it will be merged and to add the necessary changes? I am always a bit lost with this git stuff...

**Comment by natask** [comment]
`git pull natask/feat/ctime-and-sort`

**Comment by natask** [comment]
by the way, is the query function more preformant in your local copy? querying for tolinks and backlinks is costly.

**Comment by publicimageltd** [comment]
> `git pull natask/feat/ctime-and-sort`

Thanks, but it doesn't work; neither does `git pull origin natask/feat/ctime-and-sort`, or some variants thereof. It says 'could'nt find remote reference'. I understand that I can alternatively just fetch your feature branch and then merge it into a test branch, but hey, that's too much git wizardry for the moment. I'll have a look at it later; I'm busy with other work right now.

In the end, it might be that I just add these changes manually; I hope that's ok with you.

> by the way, is the query function more preformant in your local copy? querying for tolinks and backlinks is costly.

The new version is a bit more performant since it does not traverse the result list two times. But the SQL query remains the same. I have no good idea, currently, how to improve that situation, and I will just wait what `org-roam v2` will bring. The problem is that the whole concept of `delve` is centered around the idea of 'following links', so it seems reasonable to present the most important links in a summary fashion together with the item. Only alternative I can think of currently is displaying this information rather on demand, instead of providing it automacally, but to me, that seems rather unhandy right now. I'll think about it.

**Comment by publicimageltd** [comment]
OK got it working on my machine. ctime fields remains empty, however, the plist returned by the meta field does not offer the property ctime. Looking at this document, https://www.unix.com/tips-and-tutorials/20526-mtime-ctime-atime.html, however, I figure that ctime is not really necessary, since it only differs from mtime because it registers modifications of ownership and the like. So I'd suggest that we'd drop supporting ctime.

**Comment by natask** [comment]
ctime as in creation or birth time (windows terminology). It is not part of the main branch org-roam database. I don't recommend including it until it is supported in main branch. It doesn't break delve's functionality though so there isn't harm from leaving it in the codebase, I suppose, in anticipation that upstream will support it in v2. If you are interested look at [my branch](https://github.com/natask/org-roam/tree/feat/creation-time) and [discussion](https://org-roam.discourse.group/t/org-roam-major-redesign/1198/77).

> > `git pull natask/feat/ctime-and-sort`
> 
> Thanks, but it doesn't work; neither does `git pull origin natask/feat/ctime-and-sort`,

sorry, my mistake wrong command. I am glad you found online resources to fetch this branch.
> 
> In the end, it might be that I just add these changes manually; I hope that's ok with you.

Feel free to take only the stuff that you believe is necessary. I implemented this for my use without the intention of a pull request.

> The new version is a bit more performant since it does not traverse the result list two times.

I believe that is outside the actual query itself? If so that would indeed speed up delve for me as well.

>  But the SQL query remains the same. I have no good idea, currently, how to improve that situation, and I will just wait what `org-roam v2` will bring.

Counting tolinks and backlinks is the most expensive sql query. It is possible to manage tolinks and backlinks as file meta data. That would avoid costly sql queries. I would need upstream support though.

I removed tolinks and backlinks  from the query for myself and delve is much faster even when matching my whole database of 2500 files (I use it as to see the chronology of files I have created and modified alongside the sort functions).

**Comment by publicimageltd** [comment]
Finally merged it! You can try `delve-sort-sublist` and write functions for quick sorting now. It even sorts sublists correctly. 

Set the variable `delve-zettel-pp-time-scheme` to `(mtime ctime atime)` to have all three times presented.

Next version will be w/o backlinks and tolinks, you are right. They are too costly and not really necessary, since one can easily expand on an item to check.

**Comment by natask** [comment]
Thanks for the update.

Here are a couple things I wrote considering the new version. Feel free to incorporate them into the repo.

For lister, restricting the function applied to the list to sort didn't allow me to reverse it. So instead I made the function settable through a variable.
``` lisp
(defvar lister-apply-fun 'identity)
(defun lister--apply-fun-on-wrapped-list (l)
  "Apply FUN on L, keeping sublist structure.
L has to be a wrapped list as returned by `lister--wrap-list'."
  (declare (pure t) (side-effect-free t))
  (let (acc (walk (funcall lister-apply-fun l)))
    (while
	(let ((item    (caar walk))
	      (sublist (cdar walk)))
	  (push item acc)
	  (when (consp sublist)
	    (push (lister--apply-fun-on-wrapped-list sublist pred) acc))
	  (setq walk (cdr walk))))
    (nreverse acc)))

(defun lister-apply-fun-on-list (lister-buf &optional first last)
  "Sort all items from FIRST to LAST according to PRED.
If FIRST or LAST are nil, use the beginning or the end of the
list as boundaries.

LISTER-BUF is a lister buffer."
  (lister-with-normalized-region lister-buf first last
    (when-let* ((old-list (lister-get-all-data-tree lister-buf first last)))
      (let* ((level        (lister-get-level-at lister-buf first))
	     (wrapped-list (lister--wrap-list old-list))
	     (new-list     (lister--apply-fun-on-wrapped-list wrapped-list)))
	(lister-replace-list lister-buf new-list first last level)))))
```
The following function works as expected on an item that aren't sortable. the item's sublist is sorted instead if they exist. A useful consequence is there is no need to move cursor to the second line before sorting.

``` lisp
(defun delve-apply-fun-on-sublist (buf pos &optional next-pos)
  "Sort the sublist at POS in delve buffer BUF.
SORT-PRED has to be a function which returns the right order when
comparing two zettel items. The macro
`delve-db-zettel-sorting-pred' can be used for creating such
functions on the fly.

If called interactively, let the user select the predicate for
sorting the sublist at point."
  (interactive (list (current-buffer)
                     (point)
                     (save-excursion (foward-line) (point))))
  (unless (lister-nonempty-p buf)
    (user-error "Nothing to sort"))
  ;; check if the value at pos is valid, and also at pos + 1. if pos, select pos, if pos+1, select pos+1 both, select the smaller level,
  (let ((data (and (lister-item-p buf pos)
                   (lister-get-data buf pos)))
        (data2 (and next-pos
                    (lister-item-p buf next-pos)
                    (lister-get-data buf next-pos))))
    (let (eval-pos)
      (if (and data
               (delve-zettel-p data))
          ;; eval-pos level
          (setq eval-pos pos)
      (if (and data2
               (delve-zettel-p data2))
          (setq eval-pos next-pos)
          (user-error "For sorting, point must be on a zettel item")))
      (pcase-let* ((`(,beg ,end _ ) (lister-sublist-boundaries buf eval-pos)))
        (lister-apply-fun-on-list buf beg end)))))

(defun delve-apply-fun-on-sublist-at-point (buf)
  "Sort the sublist at point in delve buffer BUF.
SORT-PRED has to be a function which returns the right order when
comparing two zettel items. The macro
`delve-db-zettel-sorting-pred' can be used for creating such
functions on the fly.

If called interactively, let the user select the predicate for
sorting the sublist at point."
 (delve-apply-fun-on-sublist buf (point) (save-excursion (foward-line) (point))))
```

quick example using the above.
```  lisp
(defun delve-reverse-buffer (buf)
  "Refresh all items in BUF."
  (interactive (list (current-buffer)))
  (let ((lister-apply-fun 'reverse))
  (delve-apply-fun-on-sublist-at-point buf)))
```

**Comment by publicimageltd** [comment]
Thanks for the proposals! I don't understand the rationale behind them, though. 

1. The sorting algorithm for lister: Why the need to introduce `lister-apply-fun`? Reversing a list can be simply had without sorting, and sorting in reverse order is just another sorting function. I seem to miss some use case.
2. The second suggestion seems to handle the case that one wants to sort a sublist below the current item. Why put this in the same function which also sorts a list *tout court*? Is it just a convenience wrapper, because you find yourself often in the position to open a list and then want to sort it directly? 

If the latter is the use case, having both functionalities --- sorting the list at point and sorting the sublist below point - in one function seems to me confusing. So I would suggest to write a second sorting function `delve-sort-dwim`. This function could then....
 
   - Sort the sublist below, if we are on a node, else sort the whole list.
   - If called two times in a row, the second time, just reverse the list.

That seems to me a practical way to handle the use-case I imagine you are talking about.

**Comment by natask** [comment]
Both of these implementations where first pass implementations that accomplished the suggestions without studying possible side-effects. With that said, I think the core ideas behind the suggestions are valid. 
I think the first suggestion is more important/useful than the second, which is more for convenience.

1) Introduce the ability to run arbitrary function on a wrapped list. Useful for reversing a list (not possible through sort directly because it operates on a lists indices and not on comparing elements) as shown because it isn't straightforward to keep state and toggle as you suggest. The state needs to be buffer specific so that it isn't shared between different delve buffers or even delve objects if one wants to reverse sublists that have been sorted differently than other sublists (reversing a list naturally has this property) and will potentially be mapped to the state of delve objects that have sublists that can be sorted. Such state will enable certain types of features, for example sorting a sublist as it is expanded, so I think they are a good idea but ill suited for reversing a list.

   Although more wildly applicable and should be guided by application, such a modification makes the program more general and flexible and allow other types of extensions without further modification. For example, reversing a list can be decoupled from sorting a list as a separate command easily and directly. It is possible to emulate such decoupling by adding state and logic, for example, if the previously sort function is such do such etcetra but would be tideous.

   On the point of introducing global state, I realize now as a consequence of what I said above that It isn't a good idea to introduce state `lister-apply-fun` because it would be shared not only between different delve buffers but also different lister objects. It it possible to overcome this limitation but would be tedious. It would be better to implement using a function parameter that works its way down the function call instead of `lister-apply-fun` because the function to be applied can then be naturally associated with which buffer and object it called from. The way I use it within `delve-reverse-buffer` is a hint that such an approach is possible and it doesn't have the side-effects that depending on `lister-apply-fun` has.

2) Regarding the second suggestion, Its purpose is to sort the sublist of a delve object that isn't a `delve-zettel` object. For example, the original implementation fails if the cursor is on a `delve-page-search` object, while the implied intent is to sort its sublist. I admit that its purpose is not clear from its implementation. 
   In its current form, it can't open an item and then sort its sublist directly but I imagine that would be a useful feature to maintain consistency.

**Comment by natask** [comment]
here is an updated implementation using function call style. 
``` lisp
#+begin_src emacs-lisp :results none
(defun lister--apply-fun-on-wrapped-list (l fn)
  "Apply FN on L, keeping sublist structure.
L has to be a wrapped list as returned by `lister--wrap-list'."
  (declare (pure t) (side-effect-free t))
  (let (acc (walk (funcall fn l)))
    (while
	(let ((item    (caar walk))
	      (sublist (cdar walk)))
	  (push item acc)
	  (when (consp sublist)
	    (push (lister--apply-fun-on-wrapped-list sublist pred) acc))
	  (setq walk (cdr walk))))
    (nreverse acc)))

(defun lister-apply-fun-on-list (lister-buf fn &optional first last)
  "Apply FN on all items from FIRST to LAST.
If FIRST or LAST are nil, use the beginning or the end of the
list as boundaries.

LISTER-BUF is a lister buffer."
  (lister-with-normalized-region lister-buf first last
    (when-let* ((old-list (lister-get-all-data-tree lister-buf first last)))
      (let* ((level        (lister-get-level-at lister-buf first))
	     (wrapped-list (lister--wrap-list old-list))
	     (new-list     (lister--apply-fun-on-wrapped-list wrapped-list fn)))
	(lister-replace-list lister-buf new-list first last level)))))
#+end_src

#+begin_src emacs-lisp :results none
(defun delve-apply-fun-on-sublist (buf pos fn &optional next-pos)
  "Apply FN on the sublist at POS in delve buffer BUF.
NEXT-POS is used for dwim usage."
  (interactive (list (current-buffer)
                     (point)
                     (save-excursion (foward-line) (point))))
  (unless (lister-nonempty-p buf)
    (user-error "Nothing to sort"))
  (let ((data (and (lister-item-p buf pos)
                   (lister-get-data buf pos)))
        (data2 (and next-pos
                    (lister-item-p buf next-pos)
                    (lister-get-data buf next-pos))))
    (let (eval-pos)
      (if (and data
               (delve-zettel-p data))
          (setq eval-pos pos)
      (if (and data2
               (delve-zettel-p data2))
          (setq eval-pos next-pos)
          (user-error "For sorting, point must be on a zettel item")))
      (pcase-let* ((`(,beg ,end _ ) (lister-sublist-boundaries buf eval-pos)))
        (lister-apply-fun-on-list buf fn beg end)))))
#+end_src

#+begin_src emacs-lisp
(defun delve-apply-fun-on-sublist-at-point (buf fn)
  "Apply FN on the sublist at point in delve buffer BUF at point."
 (delve-apply-fun-on-sublist buf (point) fn (save-excursion (forward-line) (point))))
#+end_src

#+RESULTS:
: delve-apply-fun-on-sublist-at-point

#+begin_src emacs-lisp :results none 
(defun delve-reverse-buffer (buf)
  "Refresh all items in BUF."
  (interactive (list (current-buffer)))
  (delve-apply-fun-on-sublist-at-point buf 'reverse))

(defun delve-sort-buffer-by-pred (buf pred)
  "Refresh all items in BUF."
  (interactive (list (current-buffer)))
  (let ((lister-apply-fun (lambda (l) (cl-sort l pred :key #'car))))
  (delve-apply-fun-on-sublist-at-point buf lister-apply-fun)))

(defun delve-sort-buffer-by-atime (buf)
  "Refresh all items in BUF."
  (interactive (list (current-buffer)))
  (delve-sort-buffer-by-pred buf (delve-db-zettel-sorting-pred #'time-less-p  'atime :not)))

(defun delve-sort-buffer-by-mtime (buf)
  "Refresh all items in BUF."
  (interactive (list (current-buffer)))
  (delve-sort-buffer-by-pred buf (delve-db-zettel-sorting-pred #'time-less-p  'mtime :not)))

(defun delve-sort-buffer-by-ctime (buf)
  "Refresh all items in BUF."
  (interactive (list (current-buffer)))
  (delve-sort-buffer-by-pred buf (delve-db-zettel-sorting-pred #'time-less-p  'ctime :not)))
#+end_src
```

**Comment by publicimageltd** [comment]
Now I see! You are suggesting a generalization: Instead of sorting "wrapped" lists, we apply all kind of functions on them. "Sorting" is then just a subset. The advantage, you are right, is that we can easily e.g. "reverse" a list while keeping the sublist hierarchies. So it is useful for all functions which change the order of a list.

Cool! I will implement that in `lister` and then change `delve` accordingly. Might take a while, though. So if you want to speed it up, you might as well make a PR for the `lister`; and take the credit. I'd adopt your suggestion, anyways. Only thing is that I might call the generalized function `lister-reorder-list`, to indicate its purpose and to differentiate it more clearly from "walking" a list, which also does apply a function.

**Comment by publicimageltd** [comment]
@natask New lister version 0.7 now features "reordering" as an abstraction of the sorting function

**Pull request merged**
